### PR TITLE
Use scipy optimize to find expected excess counts

### PR DESCRIPTION
**Pull request by kbruegge**
Hello,

this simplifies the method which estimated the number of excess counts needed to reach the target significance. The resulting excess numbers are within one or two decimals of the old method. The first test case fails however. I'm curious where the number comes from. Is it some objective *truth* calculated by another program?

### CODE REVIEW

**Comment by kbruegge** [comment]
@cdeil do you have an idea on how to get some values we could use for comparison in our unit tests?

**Comment by kbruegge** [comment]
@bkhelifi @cdeil I see you guys closed the pull request https://github.com/gammapy/gammapy/pull/1053 .  Are you planning to reopen it for the new IRFs?

**Comment by kbruegge** [comment]
I reopend this here: https://github.com/gammapy/gammapy/pull/1123

**Comment by cdeil** [comment]
@mackaiver - Sorry, I had missed this PR!
@bkhelifi and I will have a look at the one you opened just now tomorrow.

**Pull request closed without merging**
